import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {
			fontFamily: {
				sans: ['Inter', 'system-ui', 'sans-serif'],
				display: ['"HW Cigars"', 'serif'],
			},
			colors: {
				body: 'var(--color-body)',
				canvas: 'var(--color-canvas)',
			},
			textColor: {
				primary: 'var(--text-primary)',
				secondary: 'var(--text-secondary)',
				tertiary: 'var(--text-tertiary)',
			},
			width: {
				xs: '20rem',
				sm: '24rem',
				md: '28rem',
				lg: '32rem',
				xl: '36rem',
				'2xl': '42rem',
				'3xl': '48rem',
				'4xl': '56rem',
				'5xl': '64rem',
				'6xl': '72rem',
				'7xl': '80rem',
			},
			minWidth: {
				xs: '20rem',
				sm: '24rem',
				md: '28rem',
				lg: '32rem',
				xl: '36rem',
				'2xl': '42rem',
				'3xl': '48rem',
				'4xl': '56rem',
				'5xl': '64rem',
				'6xl': '72rem',
				'7xl': '80rem',
			},
			typography: ({ theme }) => ({
				neutral: {
					css: {
						'--tw-prose-body': theme('colors.neutral.700'),
						'--tw-prose-headings': theme('colors.neutral.900'),
						'--tw-prose-links': theme('colors.neutral.900'),
						'--tw-prose-bold': theme('colors.neutral.900'),
						'--tw-prose-counters': theme('colors.neutral.500'),
						'--tw-prose-bullets': theme('colors.neutral.300'),
						'--tw-prose-hr': theme('colors.neutral.200'),
						'--tw-prose-quotes': theme('colors.neutral.900'),
						'--tw-prose-quote-borders': theme('colors.neutral.200'),
						'--tw-prose-captions': theme('colors.neutral.500'),
						'--tw-prose-code': theme('colors.neutral.900'),
						'--tw-prose-pre-code': theme('colors.neutral.200'),
						'--tw-prose-pre-bg': theme('colors.neutral.900'),
						'--tw-prose-th-borders': theme('colors.neutral.300'),
						'--tw-prose-td-borders': theme('colors.neutral.200'),
						'--tw-prose-invert-body': theme('colors.neutral.300'),
						'--tw-prose-invert-headings': theme('colors.neutral.50'),
						'--tw-prose-invert-links': theme('colors.neutral.50'),
						'--tw-prose-invert-bold': theme('colors.neutral.50'),
						'--tw-prose-invert-counters': theme('colors.neutral.400'),
						'--tw-prose-invert-bullets': theme('colors.neutral.600'),
						'--tw-prose-invert-hr': theme('colors.neutral.700'),
						'--tw-prose-invert-quotes': theme('colors.neutral.100'),
						'--tw-prose-invert-quote-borders': theme('colors.neutral.700'),
						'--tw-prose-invert-captions': theme('colors.neutral.400'),
						'--tw-prose-invert-code': theme('colors.neutral.50'),
						'--tw-prose-invert-pre-code': theme('colors.neutral.200'),
						'--tw-prose-invert-pre-bg': theme('colors.neutral.900'),
						'--tw-prose-invert-th-borders': theme('colors.neutral.600'),
						'--tw-prose-invert-td-borders': theme('colors.neutral.700'),
					},
				},
			}),
		},
	},
	plugins: [typography],
};
